The previous commit still broke GlobalModelOtherTest on Mac OSX because of it would printout the result of the NoClassDefFoundError.
git-svn-id: file:///tmp/test-svn/trunk@1765 fe72c1cf-3628-48e9-8b72-1c46755d3cff